# OPEN AI API Details

API_KEY = "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"
TEXT_MODEL = "gpt-4o-mini"

# TOKEN DETAILS
AVERAGE_TOKENS_PER_WORD = 5
